//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenNamAnh_K66CNPMB.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponse HelloWorld(NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponse> HelloWorldAsync(NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name LayGioHeThongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayGioHeThong", ReplyAction="*")]
        NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponse LayGioHeThong(NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayGioHeThong", ReplyAction="*")]
        System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponse> LayGioHeThongAsync(NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest request);
        
        // CODEGEN: Generating message contract since element name TinhTongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TinhTong", ReplyAction="*")]
        NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponse TinhTong(NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TinhTong", ReplyAction="*")]
        System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponse> TinhTongAsync(NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LayGioHeThongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LayGioHeThong", Namespace="http://tempuri.org/", Order=0)]
        public NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequestBody Body;
        
        public LayGioHeThongRequest() {
        }
        
        public LayGioHeThongRequest(NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LayGioHeThongRequestBody {
        
        public LayGioHeThongRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LayGioHeThongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LayGioHeThongResponse", Namespace="http://tempuri.org/", Order=0)]
        public NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponseBody Body;
        
        public LayGioHeThongResponse() {
        }
        
        public LayGioHeThongResponse(NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LayGioHeThongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LayGioHeThongResult;
        
        public LayGioHeThongResponseBody() {
        }
        
        public LayGioHeThongResponseBody(string LayGioHeThongResult) {
            this.LayGioHeThongResult = LayGioHeThongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TinhTongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TinhTong", Namespace="http://tempuri.org/", Order=0)]
        public NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequestBody Body;
        
        public TinhTongRequest() {
        }
        
        public TinhTongRequest(NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TinhTongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public TinhTongRequestBody() {
        }
        
        public TinhTongRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TinhTongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TinhTongResponse", Namespace="http://tempuri.org/", Order=0)]
        public NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponseBody Body;
        
        public TinhTongResponse() {
        }
        
        public TinhTongResponse(NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TinhTongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TinhTongResult;
        
        public TinhTongResponseBody() {
        }
        
        public TinhTongResponseBody(string TinhTongResult) {
            this.TinhTongResult = TinhTongResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap>, NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponse NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap.HelloWorld(NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest inValue = new NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest();
            inValue.Body = new NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequestBody();
            NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponse retVal = ((NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponse> NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap.HelloWorldAsync(NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest inValue = new NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequest();
            inValue.Body = new NguyenNamAnh_K66CNPMB.ServiceReference1.HelloWorldRequestBody();
            return ((NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponse NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap.LayGioHeThong(NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest request) {
            return base.Channel.LayGioHeThong(request);
        }
        
        public string LayGioHeThong() {
            NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest inValue = new NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest();
            inValue.Body = new NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequestBody();
            NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponse retVal = ((NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap)(this)).LayGioHeThong(inValue);
            return retVal.Body.LayGioHeThongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponse> NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap.LayGioHeThongAsync(NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest request) {
            return base.Channel.LayGioHeThongAsync(request);
        }
        
        public System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongResponse> LayGioHeThongAsync() {
            NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest inValue = new NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequest();
            inValue.Body = new NguyenNamAnh_K66CNPMB.ServiceReference1.LayGioHeThongRequestBody();
            return ((NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap)(this)).LayGioHeThongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponse NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap.TinhTong(NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest request) {
            return base.Channel.TinhTong(request);
        }
        
        public string TinhTong(int a, int b) {
            NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest inValue = new NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest();
            inValue.Body = new NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponse retVal = ((NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap)(this)).TinhTong(inValue);
            return retVal.Body.TinhTongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponse> NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap.TinhTongAsync(NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest request) {
            return base.Channel.TinhTongAsync(request);
        }
        
        public System.Threading.Tasks.Task<NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongResponse> TinhTongAsync(int a, int b) {
            NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest inValue = new NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequest();
            inValue.Body = new NguyenNamAnh_K66CNPMB.ServiceReference1.TinhTongRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((NguyenNamAnh_K66CNPMB.ServiceReference1.WebServiceSoap)(this)).TinhTongAsync(inValue);
        }
    }
}
